name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: '26'

      - name: Install dependencies
        run: npm install  --ignore-scripts # not npm ci — lock file is generated on Windows

      - name: Audit dependencies
        run: npm audit --audit-level=high

      - name: Build
        run: npm run build
